const preloadedQuestions =
[{"japanese":"あ","kanji":"","romanji":"","english":"A","category":"Hiragana"},
{"japanese":"い","kanji":"","romanji":"","english":"I","category":"Hiragana"},
{"japanese":"う","kanji":"","romanji":"","english":"U","category":"Hiragana"},
{"japanese":"え","kanji":"","romanji":"","english":"E","category":"Hiragana"},
{"japanese":"お","kanji":"","romanji":"","english":"O","category":"Hiragana"},
{"japanese":"か","kanji":"","romanji":"","english":"Ka","category":"Hiragana"},
{"japanese":"き","kanji":"","romanji":"","english":"Ki","category":"Hiragana"},
{"japanese":"く","kanji":"","romanji":"","english":"Ku","category":"Hiragana"},
{"japanese":"け","kanji":"","romanji":"","english":"Ke","category":"Hiragana"},
{"japanese":"さ","kanji":"","romanji":"","english":"Sa","category":"Hiragana"},
{"japanese":"し","kanji":"","romanji":"","english":"Shi","category":"Hiragana"},
{"japanese":"す","kanji":"","romanji":"","english":"Su","category":"Hiragana"},
{"japanese":"せ","kanji":"","romanji":"","english":"Se","category":"Hiragana"},
{"japanese":"そ","kanji":"","romanji":"","english":"So","category":"Hiragana"},
{"japanese":"た","kanji":"","romanji":"","english":"Ta","category":"Hiragana"},
{"japanese":"ち","kanji":"","romanji":"","english":"Chi","category":"Hiragana"},
{"japanese":"つ","kanji":"","romanji":"","english":"Tsu","category":"Hiragana"},
{"japanese":"て","kanji":"","romanji":"","english":"Te","category":"Hiragana"},
{"japanese":"と","kanji":"","romanji":"","english":"To","category":"Hiragana"},
{"japanese":"な","kanji":"","romanji":"","english":"Na","category":"Hiragana"},
{"japanese":"に","kanji":"","romanji":"","english":"Ni","category":"Hiragana"},
{"japanese":"ぬ","kanji":"","romanji":"","english":"Nu","category":"Hiragana"},
{"japanese":"ね","kanji":"","romanji":"","english":"Ne","category":"Hiragana"},
{"japanese":"の","kanji":"","romanji":"","english":"No","category":"Hiragana"},
{"japanese":"は","kanji":"","romanji":"","english":"Ha","category":"Hiragana"},
{"japanese":"ひ","kanji":"","romanji":"","english":"Hi","category":"Hiragana"},
{"japanese":"ふ","kanji":"","romanji":"","english":"Fu","category":"Hiragana"},
{"japanese":"へ","kanji":"","romanji":"","english":"He","category":"Hiragana"},
{"japanese":"ほ","kanji":"","romanji":"","english":"Ho","category":"Hiragana"},
{"japanese":"ま","kanji":"","romanji":"","english":"Ma","category":"Hiragana"},
{"japanese":"み","kanji":"","romanji":"","english":"Mi","category":"Hiragana"},
{"japanese":"む","kanji":"","romanji":"","english":"Mu","category":"Hiragana"},
{"japanese":"め","kanji":"","romanji":"","english":"Me","category":"Hiragana"},
{"japanese":"も","kanji":"","romanji":"","english":"Mo","category":"Hiragana"},
{"japanese":"や","kanji":"","romanji":"","english":"Ya","category":"Hiragana"},
{"japanese":"ゆ","kanji":"","romanji":"","english":"Yu","category":"Hiragana"},
{"japanese":"よ","kanji":"","romanji":"","english":"Yo","category":"Hiragana"},
{"japanese":"ら","kanji":"","romanji":"","english":"Ra","category":"Hiragana"},
{"japanese":"り","kanji":"","romanji":"","english":"Ri","category":"Hiragana"},
{"japanese":"る","kanji":"","romanji":"","english":"Ru","category":"Hiragana"},
{"japanese":"れ","kanji":"","romanji":"","english":"Re","category":"Hiragana"},
{"japanese":"ろ","kanji":"","romanji":"","english":"Ro","category":"Hiragana"},
{"japanese":"わ","kanji":"","romanji":"","english":"Wa","category":"Hiragana"},
{"japanese":"う","kanji":"","romanji":"","english":"U","category":"Hiragana"},
{"japanese":"うぇ","kanji":"","romanji":"","english":"We","category":"Hiragana"},
{"japanese":"を","kanji":"","romanji":"","english":"O","category":"Hiragana"},
{"japanese":"ん","kanji":"","romanji":"","english":"N","category":"Hiragana"},
{"japanese":"ア","kanji":"","romanji":"","english":"a","category":"Katakana"},
{"japanese":"イ","kanji":"","romanji":"","english":"i","category":"Katakana"},
{"japanese":"ウ","kanji":"","romanji":"","english":"u","category":"Katakana"},
{"japanese":"エ","kanji":"","romanji":"","english":"e","category":"Katakana"},
{"japanese":"オ","kanji":"","romanji":"","english":"o","category":"Katakana"},
{"japanese":"カ","kanji":"","romanji":"","english":"ka","category":"Katakana"},
{"japanese":"キ","kanji":"","romanji":"","english":"ki","category":"Katakana"},
{"japanese":"ク","kanji":"","romanji":"","english":"ku","category":"Katakana"},
{"japanese":"ケ","kanji":"","romanji":"","english":"ke","category":"Katakana"},
{"japanese":"コ","kanji":"","romanji":"","english":"ko","category":"Katakana"},
{"japanese":"サ","kanji":"","romanji":"","english":"sa","category":"Katakana"},
{"japanese":"シ","kanji":"","romanji":"","english":"shi","category":"Katakana"},
{"japanese":"ス","kanji":"","romanji":"","english":"su","category":"Katakana"},
{"japanese":"セ","kanji":"","romanji":"","english":"se","category":"Katakana"},
{"japanese":"ソ","kanji":"","romanji":"","english":"so","category":"Katakana"},
{"japanese":"タ","kanji":"","romanji":"","english":"ta","category":"Katakana"},
{"japanese":"チ","kanji":"","romanji":"","english":"chi","category":"Katakana"},
{"japanese":"ツ","kanji":"","romanji":"","english":"tsu","category":"Katakana"},
{"japanese":"テ","kanji":"","romanji":"","english":"te","category":"Katakana"},
{"japanese":"ト","kanji":"","romanji":"","english":"to","category":"Katakana"},
{"japanese":"ナ","kanji":"","romanji":"","english":"na","category":"Katakana"},
{"japanese":"ニ","kanji":"","romanji":"","english":"ni","category":"Katakana"},
{"japanese":"ヌ","kanji":"","romanji":"","english":"nu","category":"Katakana"},
{"japanese":"ネ","kanji":"","romanji":"","english":"ne","category":"Katakana"},
{"japanese":"ノ","kanji":"","romanji":"","english":"no","category":"Katakana"},
{"japanese":"ハ","kanji":"","romanji":"","english":"ha","category":"Katakana"},
{"japanese":"ヒ","kanji":"","romanji":"","english":"hi","category":"Katakana"},
{"japanese":"フ","kanji":"","romanji":"","english":"fu","category":"Katakana"},
{"japanese":"ヘ","kanji":"","romanji":"","english":"he","category":"Katakana"},
{"japanese":"ホ","kanji":"","romanji":"","english":"ho","category":"Katakana"},
{"japanese":"マ","kanji":"","romanji":"","english":"ma","category":"Katakana"},
{"japanese":"ミ","kanji":"","romanji":"","english":"mi","category":"Katakana"},
{"japanese":"ム","kanji":"","romanji":"","english":"mu","category":"Katakana"},
{"japanese":"メ","kanji":"","romanji":"","english":"me","category":"Katakana"},
{"japanese":"モ","kanji":"","romanji":"","english":"mo","category":"Katakana"},
{"japanese":"ヤ","kanji":"","romanji":"","english":"ya","category":"Katakana"},
{"japanese":"ユ","kanji":"","romanji":"","english":"yu","category":"Katakana"},
{"japanese":"ヨ","kanji":"","romanji":"","english":"yo","category":"Katakana"},
{"japanese":"ラ","kanji":"","romanji":"","english":"ra","category":"Katakana"},
{"japanese":"リ","kanji":"","romanji":"","english":"ri","category":"Katakana"},
{"japanese":"ル","kanji":"","romanji":"","english":"ru","category":"Katakana"},
{"japanese":"レ","kanji":"","romanji":"","english":"re","category":"Katakana"},
{"japanese":"ロ","kanji":"","romanji":"","english":"ro","category":"Katakana"},
{"japanese":"ワ","kanji":"","romanji":"","english":"wa","category":"Katakana"},
{"japanese":"ヲ","kanji":"","romanji":"","english":"wo","category":"Katakana"},
{"japanese":"ン","kanji":"","romanji":"","english":"n","category":"Katakana"},
{"japanese":"あう","kanji":"会う","romanji":"au","english":"to meet","category":"Dictionary Form Words (N5)"},
{"japanese":"あう","kanji":"合う","romanji":"au","english":"to fit","category":"Dictionary Form Words (N5)"},
{"japanese":"あたま","kanji":"頭","romanji":"atama","english":"head","category":"Dictionary Form Words (N5)"},
{"japanese":"あめ","kanji":"雨","romanji":"ame","english":"rain","category":"Dictionary Form Words (N5)"},
{"japanese":"いく","kanji":"行く","romanji":"iku","english":"to go","category":"Dictionary Form Words (N5)"},
{"japanese":"いぬ","kanji":"犬","romanji":"inu","english":"dog","category":"Dictionary Form Words (N5)"},
{"japanese":"いま","kanji":"今","romanji":"ima","english":"now","category":"Dictionary Form Words (N5)"},
{"japanese":"おおきい","kanji":"大きい","romanji":"ookii","english":"big","category":"Dictionary Form Words (N5)"},
{"japanese":"おかね","kanji":"お金","romanji":"okane","english":"money","category":"Dictionary Form Words (N5)"},
{"japanese":"おいしい","kanji":"美味しい","romanji":"oishii","english":"delicious","category":"Dictionary Form Words (N5)"},
{"japanese":"かう","kanji":"買う","romanji":"kau","english":"to buy","category":"Dictionary Form Words (N5)"},
{"japanese":"かぜ","kanji":"風","romanji":"kaze","english":"wind","category":"Dictionary Form Words (N5)"},
{"japanese":"かみ","kanji":"紙","romanji":"kami","english":"paper","category":"Dictionary Form Words (N5)"},
{"japanese":"きく","kanji":"聞く","romanji":"kiku","english":"to listen","category":"Dictionary Form Words (N5)"},
{"japanese":"きれい","kanji":"綺麗","romanji":"kirei","english":"beautiful","category":"Dictionary Form Words (N5)"},
{"japanese":"くる","kanji":"来る","romanji":"kuru","english":"to come","category":"Dictionary Form Words (N5)"},
{"japanese":"さかな","kanji":"魚","romanji":"sakana","english":"fish","category":"Dictionary Form Words (N5)"},
{"japanese":"しる","kanji":"知る","romanji":"shiru","english":"to know","category":"Dictionary Form Words (N5)"},
{"japanese":"たべる","kanji":"食べる","romanji":"taberu","english":"to eat","category":"Dictionary Form Words (N5)"},
{"japanese":"ちいさい","kanji":"小さい","romanji":"chiisai","english":"small","category":"Dictionary Form Words (N5)"},
{"japanese":"ともだち","kanji":"友達","romanji":"tomodachi","english":"friend","category":"Dictionary Form Words (N5)"},
{"japanese":"ねる","kanji":"寝る","romanji":"neru","english":"to sleep","category":"Dictionary Form Words (N5)"},
{"japanese":"はな","kanji":"花","romanji":"hana","english":"flower","category":"Dictionary Form Words (N5)"},
{"japanese":"みる","kanji":"見る","romanji":"miru","english":"to see","category":"Dictionary Form Words (N5)"},
{"japanese":"やる","kanji":"やる","romanji":"yaru","english":"to do","category":"Dictionary Form Words (N5)"},
{"japanese":"あさ","kanji":"朝","romanji":"asa","english":"morning","category":"Dictionary Form Words (N5)"},
{"japanese":"あたる","kanji":"当たる","romanji":"ataru","english":"to hit","category":"Dictionary Form Words (N5)"},
{"japanese":"あめ","kanji":"飴","romanji":"ame","english":"candy","category":"Dictionary Form Words (N5)"},
{"japanese":"いえ","kanji":"家","romanji":"ie","english":"house","category":"Dictionary Form Words (N5)"},
{"japanese":"いき","kanji":"行き","romanji":"iki","english":"going","category":"Dictionary Form Words (N5)"},
{"japanese":"いっしょ","kanji":"一緒","romanji":"issho","english":"together","category":"Dictionary Form Words (N5)"},
{"japanese":"うた","kanji":"歌","romanji":"uta","english":"song","category":"Dictionary Form Words (N5)"},
{"japanese":"えいが","kanji":"映画","romanji":"eiga","english":"movie","category":"Dictionary Form Words (N5)"},
{"japanese":"おい","kanji":"おい","romanji":"oi","english":"hey","category":"Dictionary Form Words (N5)"},
{"japanese":"およぐ","kanji":"泳ぐ","romanji":"oyogu","english":"to swim","category":"Dictionary Form Words (N5)"},
{"japanese":"かかる","kanji":"かかる","romanji":"kakaru","english":"to take (time)","category":"Dictionary Form Words (N5)"},
{"japanese":"かた","kanji":"方","romanji":"kata","english":"person (polite)","category":"Dictionary Form Words (N5)"},
{"japanese":"き","kanji":"木","romanji":"ki","english":"tree","category":"Dictionary Form Words (N5)"},
{"japanese":"くつ","kanji":"靴","romanji":"kutsu","english":"shoes","category":"Dictionary Form Words (N5)"},
{"japanese":"けさ","kanji":"今朝","romanji":"kesa","english":"this morning","category":"Dictionary Form Words (N5)"},
{"japanese":"こうえん","kanji":"公園","romanji":"kouen","english":"park","category":"Dictionary Form Words (N5)"},
{"japanese":"さく","kanji":"咲く","romanji":"saku","english":"to bloom","category":"Dictionary Form Words (N5)"},
{"japanese":"しずか","kanji":"静か","romanji":"shizuka","english":"quiet","category":"Dictionary Form Words (N5)"},
{"japanese":"すき","kanji":"好き","romanji":"suki","english":"to like","category":"Dictionary Form Words (N5)"},
{"japanese":"せんせい","kanji":"先生","romanji":"sensei","english":"teacher","category":"Dictionary Form Words (N5)"},
{"japanese":"たかい","kanji":"高い","romanji":"takai","english":"tall/expensive","category":"Dictionary Form Words (N5)"},
{"japanese":"ちかい","kanji":"近い","romanji":"chikai","english":"near","category":"Dictionary Form Words (N5)"},
{"japanese":"とおい","kanji":"遠い","romanji":"tooi","english":"far","category":"Dictionary Form Words (N5)"},
{"japanese":"なか","kanji":"中","romanji":"naka","english":"inside","category":"Dictionary Form Words (N5)"},
{"japanese":"はやい","kanji":"速い","romanji":"hayai","english":"fast","category":"Dictionary Form Words (N5)"},
{"japanese":"まち","kanji":"町","romanji":"machi","english":"town","category":"Dictionary Form Words (N5)"},
{"japanese":"みせ","kanji":"店","romanji":"mise","english":"shop","category":"Dictionary Form Words (N5)"},
{"japanese":"もり","kanji":"森","romanji":"mori","english":"forest","category":"Dictionary Form Words (N5)"},
{"japanese":"やすい","kanji":"安い","romanji":"yasui","english":"cheap","category":"Dictionary Form Words (N5)"}
];