const preloadedQuestions =
[
{"japanese":"うめ","kanji":" ","romanji":"ume","english":"sea","category":" chapter five "},
{"japanese":"きって","kanji":" ","romanji":"kitte","english":"postal stamps","category":" chapter five "},
{"japanese":"きっぷ","kanji":" ","romanji":"kippu","english":"ticket","category":" chapter five "},
{"japanese":"サーフィン","kanji":" ","romanji":"safin","english":"surfing","category":" chapter five "},
{"japanese":"しゅくだい","kanji":" ","romanji":"shukudai","english":"homework","category":" chapter five "},
{"japanese":"たべもの","kanji":" ","romanji":"tabemono","english":"food","category":" chapter five "},
{"japanese":"てんじょうび","kanji":" ","romanji":"tanjoubi","english":"birthday","category":" chapter five "},
{"japanese":"テスト","kanji":" ","romanji":"tesuto","english":"test","category":" chapter five "},
{"japanese":"てんき","kanji":" ","romanji":"tenki","english":"weather","category":" chapter five "},
{"japanese":"のみもの","kanji":" ","romanji":"nomimono","english":"drink","category":" chapter five "},
{"japanese":"はがき","kanji":" ","romanji":"hagaki","english":"postcard","category":" chapter five "},
{"japanese":"バス","kanji":" ","romanji":"hikouki","english":"bus","category":" chapter five "},
{"japanese":"へや","kanji":" ","romanji":"heya","english":"room","category":" chapter five "},
{"japanese":"ぽく","kanji":" ","romanji":"poku","english":"I (used by men)","category":" chapter five "},
{"japanese":"りょこう","kanji":" ","romanji":"ryokou","english":"travel","category":" chapter five "},
{"japanese":"やすみ","kanji":" ","romanji":"yasumi","english":"holiday;day off; abscence","category":" chapter five "},
{"japanese":"あたらしい","kanji":" ","romanji":"atarashi","english":"new","category":" chapter five "},
{"japanese":"あつい","kanji":" ","romanji":"atsui","english":"hot","category":" chapter five "},
{"japanese":"いそがしい","kanji":" ","romanji":"isogashi","english":"busy","category":" chapter five "},
{"japanese":"おおきい","kanji":" ","romanji":"ooki","english":"big","category":" chapter five "},
{"japanese":"おもしろい","kanji":" ","romanji":"omoshiroi","english":"","category":" chapter five "},
{"japanese":"こわい","kanji":" ","romanji":"kowai","english":"scary; frightening","category":" chapter five "},
{"japanese":"さむい","kanji":" ","romanji":"samui","english":"cold","category":" chapter five "},
{"japanese":"たのし","kanji":" ","romanji":"tanoshi","english":"fun","category":" chapter five "},
{"japanese":"ちいさい","kanji":" ","romanji":"chisai","english":"small","category":" chapter five "},
{"japanese":"つまらない","kanji":" ","romanji":"boring","english":"boring","category":" chapter five "},
{"japanese":"ふるい","kanji":" ","romanji":"furui","english":"old","category":" chapter five "},
{"japanese":"むずかしい","kanji":" ","romanji":"muzukashi","english":"hard; difficult","category":" chapter five "},
{"japanese":"やさしい","kanji":" ","romanji":"yasashi","english":"easy","category":" chapter five "},
{"japanese":"やすい","kanji":" ","romanji":"yasui","english":"cheap","category":" chapter five "},
{"japanese":"きらい","kanji":" ","romanji":"kirai","english":"to dislike","category":" chapter five "},
{"japanese":"きれい","kanji":" ","romanji":"kirei","english":"beautiful","category":" chapter five "},
{"japanese":"げんき","kanji":" ","romanji":"genki","english":"okay","category":" chapter five "},
{"japanese":"すき","kanji":" ","romanji":"suki","english":"to like","category":" chapter five "},
{"japanese":"だいきらい","kanji":" ","romanji":"daikirai","english":"to hate","category":" chapter five "},
{"japanese":"だいすき","kanji":" ","romanji":"daisuki","english":"to love","category":" chapter five "},
{"japanese":"にぎやか","kanji":" ","romanji":"nigiyaka","english":"lively","category":" chapter five "},
{"japanese":"ひま","kanji":" ","romanji":"hima","english":"not busy","category":" chapter five "},
{"japanese":"およぐ","kanji":" ","romanji":"oyogu","english":"swim","category":" chapter five "},
{"japanese":"きく","kanji":" ","romanji":"kiku","english":"to ask","category":" chapter five "},
{"japanese":"のる","kanji":" ","romanji":"noru","english":"to ride; to board","category":" chapter five "},
{"japanese":"やる","kanji":" ","romanji":"yaru","english":"to do; perform","category":" chapter five "},
{"japanese":"でかける","kanji":" ","romanji":"dekakeru","english":"to go out","category":" chapter five "},
{"japanese":"いっしょに","kanji":" ","romanji":"isshoni","english":"together","category":" chapter five "},
{"japanese":"すごく","kanji":" ","romanji":"sugoku","english":"extremely","category":" chapter five "},
{"japanese":"それから","kanji":" ","romanji":"sorekara","english":"and then","category":" chapter five "},
{"japanese":"だいじょうぶ","kanji":" ","romanji":"daigyobu","english":"it's okay","category":" chapter five "},
{"japanese":"とても","kanji":" ","romanji":"totemo","english":"very","category":" chapter five "},
{"japanese":"どんな","kanji":" ","romanji":"douna","english":"what kind of","category":" chapter five "},
{"japanese":"～まい","kanji":" ","romanji":"mai","english":"counter (flat obeject)","category":" chapter five "},
{"japanese":"～まで","kanji":" ","romanji":"made","english":"to (a place)","category":" chapter five "},
{"japanese":"かつこいい","kanji":" ","romanji":"kakoii","english":"good looking","category":" chapter five "},
{"japanese":"おかね","kanji":" ","romanji":"okane","english":"money","category":" chapter six "},
{"japanese":"おふろ","kanji":" ","romanji":"ofuro","english":"bath","category":" chapter six "},
{"japanese":"きょかしよ","kanji":" ","romanji":"kyokashiyo","english":"text book","category":" chapter six "},
{"japanese":"こんしゅ","kanji":" ","romanji":"konshu","english":"this week","category":" chapter six "},
{"japanese":"しみんびょういん。","kanji":" ","romanji":"shiminbyoin","english":"municiple hospital","category":" chapter six "},
{"japanese":"シャワー","kanji":" ","romanji":"showa","english":"shower","category":" chapter six "},
{"japanese":"すぎ","kanji":" ","romanji":"sugi","english":"next","category":" chapter six "},
{"japanese":"でんき","kanji":" ","romanji":"denki","english":"electricity","category":" chapter six "},
{"japanese":"でんしゃ","kanji":" ","romanji":"densha","english":"train","category":" chapter six "},
{"japanese":"にもす","kanji":" ","romanji":"nimotsu","english":"baggage","category":" chapter six "},
{"japanese":"パソコン。","kanji":" ","romanji":"pasocon","english":"personal computer","category":" chapter six "},
{"japanese":"ページ","kanji":" ","romanji":"pagi","english":"page","category":" chapter six "},
{"japanese":"まど","kanji":" ","romanji":"mado","english":"window","category":" chapter six "},
{"japanese":"よる","kanji":" ","romanji":"yoru","english":"night","category":" chapter six "},
{"japanese":"らいしょう","kanji":" ","romanji":"raishu","english":"next week","category":" chapter six "},
{"japanese":"らいねん","kanji":" ","romanji":"raihen","english":"next year","category":" chapter six "},
{"japanese":"たいへん","kanji":" ","romanji":"taihen","english":"hard","category":" chapter six "},
{"japanese":"あそぶ","kanji":" ","romanji":"asobu","english":"play","category":" chapter six "},
{"japanese":"いそぐ","kanji":" ","romanji":"isogu","english":"hurry","category":" chapter six "},
{"japanese":"おふろにはいる","kanji":" ","romanji":"ofuronihairu","english":"to take a bath","category":" chapter six "},
{"japanese":"すわる","kanji":" ","romanji":"suwaru","english":"to sit down","category":" chapter six "},
{"japanese":"たつ","kanji":" ","romanji":"tatsu","english":"to stand up","category":" chapter six "},
{"japanese":"かえす","kanji":" ","romanji":"kaesu","english":"to return","category":" chapter six "},
{"japanese":"けす","kanji":" ","romanji":"keisu","english":"turn off","category":" chapter six "},
{"japanese":"しね","kanji":" ","romanji":"shine","english":"to die","category":" chapter six "},
{"japanese":"たばこおすう","kanji":" ","romanji":"tabakoosu","english":"to smoke","category":" chapter six "},
{"japanese":"つかう","kanji":" ","romanji":"tsukau","english":"to use","category":" chapter six "},
{"japanese":"てつだう","kanji":" ","romanji":"tetsudau","english":"to help","category":" chapter six "},
{"japanese":"はいる","kanji":" ","romanji":"hairu","english":"enter","category":" chapter six "},
{"japanese":"もつ","kanji":" ","romanji":"motsu","english":"carry/hold","category":" chapter six "},
{"japanese":"やすめ","kanji":" ","romanji":"yasumu","english":"absent/rest","category":" chapter six "},
{"japanese":"あける","kanji":" ","romanji":"akeiru","english":"open","category":" chapter six "},
{"japanese":"おしえる","kanji":" ","romanji":"oshieru","english":"teach/instruct","category":" chapter six "},
{"japanese":"おりる","kanji":" ","romanji":"oriru","english":"to get off","category":" chapter six "},
{"japanese":"かりる","kanji":" ","romanji":"kariru","english":"to borrow","category":" chapter six "},
{"japanese":"しめる","kanji":" ","romanji":"shimeru","english":"to close","category":" chapter six "},
{"japanese":"シャワーをあびる","kanji":" ","romanji":"showaoabiru","english":"to take a shower","category":" chapter six "},
{"japanese":"つける","kanji":" ","romanji":"tsukeru","english":"to turn on","category":" chapter six "},
{"japanese":"でんわおかける","kanji":" ","romanji":"denwaokakeru","english":"to make a call","category":" chapter six "},
{"japanese":"わすれる","kanji":" ","romanji":"wasureru","english":"to forget","category":" chapter six "},
{"japanese":"つれてくる","kanji":" ","romanji":"tsuretekuru","english":"to bring (a person)","category":" chapter six "},
{"japanese":"もってくる","kanji":" ","romanji":"motsutekuru","english":"to bring (a thing)","category":" chapter six "},
{"japanese":"あとで","kanji":" ","romanji":"atode","english":"later on","category":" chapter six "},
{"japanese":"あそく","kanji":" ","romanji":"asoku","english":"do something (later)","category":" chapter six "},
{"japanese":"から","kanji":" ","romanji":"kara","english":"because","category":" chapter six "},
{"japanese":"けっこうです","kanji":" ","romanji":"kekkoudesu","english":"that woule be fine","category":" chapter six "},
{"japanese":"すぐ","kanji":" ","romanji":"sugu","english":"right away","category":" chapter six "},
{"japanese":"ほんとうですか","kanji":" ","romanji":"hontoudesuka","english":"really","category":" chapter six "},
{"japanese":"ゆっくる","kanji":" ","romanji":"yukkuru","english":"slowly; leisurely","category":" chapter six "},
{"japanese":"あね","kanji":"","romanji":"ane","english":"(my) older sister","category":" Chapter Seven "},
{"japanese":"アパート","kanji":"","romanji":"apato","english":"apartment","category":" Chapter Seven "},
{"japanese":"いもうと","kanji":"","romanji":"imouto","english":"younger sister","category":" Chapter Seven "},
{"japanese":"うた","kanji":"","romanji":"uta","english":"song","category":" Chapter Seven "},
{"japanese":"おじいさん","kanji":"","romanji":"ojiisan","english":"grandfather; old man","category":" Chapter Seven "},
{"japanese":"おとうと","kanji":"","romanji":"otouto","english":"younger brother","category":" Chapter Seven "},
{"japanese":"おとこのひと","kanji":"","romanji":"otokonohito","english":"man","category":" Chapter Seven "},
{"japanese":"おにいさん","kanji":"","romanji":"aniisan","english":"older brother","category":" Chapter Seven "},
{"japanese":"おねえさん","kanji":"","romanji":"oneesan","english":"older sister","category":" Chapter Seven "},
{"japanese":"おばあさん","kanji":"","romanji":"obaasan","english":"grandma; old woman","category":" Chapter Seven "},
{"japanese":"おんなのひと","kanji":"","romanji":"onnanohito","english":"woman","category":" Chapter Seven "},
{"japanese":"かいしゃ","kanji":"","romanji":"kaisha","english":"company","category":" Chapter Seven "},
{"japanese":"かぞく","kanji":"","romanji":"kazoku","english":"family","category":" Chapter Seven "},
{"japanese":"かみ","kanji":"","romanji":"kami","english":"hair","category":" Chapter Seven "},
{"japanese":"きょうだい","kanji":"","romanji":"kyoudai","english":"siblings","category":" Chapter Seven "},
{"japanese":"くさ","kanji":"","romanji":"kusa","english":"mouth","category":" Chapter Seven "},
{"japanese":"くに","kanji":"","romanji":"kuni","english":"country; place of origin;","category":" Chapter Seven "},
{"japanese":"かるま","kanji":"","romanji":"karuma","english":"car","category":" Chapter Seven "},
{"japanese":"ゲーム","kanji":"","romanji":"gemu","english":"game","category":" Chapter Seven "},
{"japanese":"コンビニ","kanji":"","romanji":"conbini","english":"convenience store","category":" Chapter Seven "},
{"japanese":"サークル","kanji":"","romanji":"sakuru","english":"club activity","category":" Chapter Seven "},
{"japanese":"しょくどう","kanji":"","romanji":"shokudou","english":"diner","category":" Chapter Seven "},
{"japanese":"ちち","kanji":"","romanji":"chichi","english":"(my) father","category":" Chapter Seven "},
{"japanese":"ディーブイディー (DVD)","kanji":"","romanji":"","english":"DVD","category":" Chapter Seven "},
{"japanese":"はは","kanji":"","romanji":"haha","english":"(my) mother","category":" Chapter Seven "},
{"japanese":"め","kanji":"","romanji":"me","english":"eye","category":" Chapter Seven "},
{"japanese":"めがね","kanji":"","romanji":"megane","english":"glasses","category":" Chapter Seven "},
{"japanese":"あたまがいい","kanji":"","romanji":"atamagaii","english":"smart (good head)","category":" Chapter Seven "},
{"japanese":"かわいい","kanji":"","romanji":"kawaii","english":"cute","category":" Chapter Seven "},
{"japanese":"せがたかい","kanji":"","romanji":"segatakai","english":"tall (stature)","category":" Chapter Seven "},
{"japanese":"せがひくい","kanji":"","romanji":"segahikui","english":"short (stature)","category":" Chapter Seven "},
{"japanese":"ながい","kanji":"","romanji":"nagai","english":"long (length)","category":" Chapter Seven "},
{"japanese":"はやい","kanji":"","romanji":"hayai","english":"fast","category":" Chapter Seven "},
{"japanese":"みじかい","kanji":"","romanji":"mijikai","english":"short (length)","category":" Chapter Seven "},
{"japanese":"しんせつな","kanji":"","romanji":"shinsetsuna","english":"kind","category":" Chapter Seven "},
{"japanese":"べんりな","kanji":"","romanji":"benrina","english":"covenient","category":" Chapter Seven "},
{"japanese":"うたう","kanji":"","romanji":"utau","english":"to sing","category":" Chapter Seven "},
{"japanese":"かふる","kanji":"","romanji":"kafuru","english":"to put on (a hat)","category":" Chapter Seven "},
{"japanese":"しる","kanji":"","romanji":"shiru","english":"to get to know","category":" Chapter Seven "},
{"japanese":"しつています","kanji":"","romanji":"shitsutaimasu","english":"I know","category":" Chapter Seven "},
{"japanese":"しりません","kanji":"","romanji":"shirimasen","english":"I do not know","category":" Chapter Seven "},
{"japanese":"すむ","kanji":"","romanji":"sumu","english":"to live","category":" Chapter Seven "},
{"japanese":"はく","kanji":"","romanji":"haku","english":"to put on (items below the waiste)","category":" Chapter Seven "},
{"japanese":"ふとる","kanji":"","romanji":"futoru","english":"to gain weight","category":" Chapter Seven "},
{"japanese":"ふとっています","kanji":"","romanji":"futotteimasu","english":"to be on the heavy side","category":" Chapter Seven "},
{"japanese":"（めがねお）かける","kanji":"","romanji":"(meganeo) kakeru","english":"to put on (glasses)","category":" Chapter Seven "},
{"japanese":"きる","kanji":"","romanji":"kiru","english":"to put on (clothes above the waiste)","category":" Chapter Seven "},
{"japanese":"つとめる","kanji":"","romanji":"tsutomeru","english":"to work for","category":" Chapter Seven "},
{"japanese":"やせる","kanji":"","romanji":"yaseru","english":"to lose weight","category":" Chapter Seven "},
{"japanese":"やせています","kanji":"","romanji":"yaseteimasu","english":"to be thin","category":" Chapter Seven "},
{"japanese":"けっこんする","kanji":"","romanji":"kekkonsuru","english":"to get married","category":" Chapter Seven "},
{"japanese":"が","kanji":"","romanji":"ga","english":"ga","category":" Chapter Seven "},
{"japanese":"なにも","kanji":"","romanji":"nanimo","english":"not...anything (+negative)","category":" Chapter Seven "},
{"japanese":"～にん","kanji":"","romanji":"~nin","english":"counter for people","category":" Chapter Seven "},
{"japanese":"ひとり","kanji":"","romanji":"hitori","english":"one person","category":" Chapter Seven "},
{"japanese":"ふたり","kanji":"","romanji":"futari","english":"two person","category":" Chapter Seven "},
{"japanese":"べつに","kanji":"","romanji":"betsuni","english":"nothing in particular (+negative)","category":" Chapter Seven "},
{"japanese":"もしもし","kanji":"","romanji":"moshimoshi","english":"hello (phone)","category":" Chapter Seven "},
{"japanese":"もちろん","kanji":"","romanji":"mochiron","english":"of course","category":" Chapter Seven "},
{"japanese":"よかったら","kanji":"","romanji":"yokattara","english":"if you like","category":" Chapter Seven"},
{"japanese":"あさって","kanji":"","romanji":"asatte","english":"the day after tomorrow","category":"Genki Chapter 8"},
{"japanese":"あめ","kanji":"","romanji":"ame","english":"rain","category":"Genki Chapter 8"},
{"japanese":"かいしゃいん","kanji":"","romanji":"kaishain","english":"office worker","category":"Genki Chapter 8"},
{"japanese":"カメラ","kanji":"","romanji":"kamera","english":"camera","category":"Genki Chapter 8"},
{"japanese":"からおけ","kanji":"","romanji":"karaoke","english":"karaoke","category":"Genki Chapter 8"},
{"japanese":"こうき","kanji":"","romanji":"kouki","english":"air","category":"Genki Chapter 8"},
{"japanese":"こくばん","kanji":"","romanji":"kokuban","english":"blackboard","category":"Genki Chapter 8"},
{"japanese":"こんげつ","kanji":"","romanji":"kongetsu","english":"this month","category":"Genki Chapter 8"},
{"japanese":"しごと","kanji":"","romanji":"shigoto","english":"work; job; occupation","category":"Genki Chapter 8"},
{"japanese":"だいがくせい","kanji":"","romanji":"daigakusei","english":"college student","category":"Genki Chapter 8"},
{"japanese":"てんきよほう","kanji":"","romanji":"tenkiyohou","english":"weather forecast","category":"Genki Chapter 8"},
{"japanese":"ところ","kanji":"","romanji":"tokoro","english":"place","category":"Genki Chapter 8"},
{"japanese":"トマト","kanji":"","romanji":"tomato","english":"tomato","category":"Genki Chapter 8"},
{"japanese":"なつ","kanji":"","romanji":"natsu","english":"summer","category":"Genki Chapter 8"},
{"japanese":"なにか","kanji":"","romanji":"nanika","english":"something","category":"Genki Chapter 8"},
{"japanese":"パーティー","kanji":"","romanji":"pati","english":"party","category":"Genki Chapter 8"},
{"japanese":"バーベキュー","kanji":"","romanji":"babekyu","english":"barbeque","category":"Genki Chapter 8"},
{"japanese":"はし","kanji":"","romanji":"hashi","english":"chopstick","category":"Genki Chapter 8"},
{"japanese":"ふゆ","kanji":"","romanji":"fuyu","english":"winter","category":"Genki Chapter 8"},
{"japanese":"ホームスティ","kanji":"","romanji":"homusutei","english":"homestay","category":"Genki Chapter 8"},
{"japanese":"まいしゅう","kanji":"","romanji":"maishu","english":"every week","category":"Genki Chapter 8"},
{"japanese":"らいげつ","kanji":"","romanji":"raigetsu","english":"next month","category":"Genki Chapter 8"},
{"japanese":"じょうずな","kanji":"","romanji":"jozu(na)","english":"skillful","category":"Genki Chapter 8"},
{"japanese":"へたな","kanji":"","romanji":"heta(na)","english":"clumsy; poor at","category":"Genki Chapter 8"},
{"japanese":"ようめいな","kanji":"","romanji":"youmei(na)","english":"famous","category":"Genki Chapter 8"},
{"japanese":"あめがふる","kanji":"","romanji":"amegafuru","english":"it rains","category":"Genki Chapter 8"},
{"japanese":"あらう","kanji":"","romanji":"arau","english":"to wash","category":"Genki Chapter 8"},
{"japanese":"いう","kanji":"","romanji":"iu","english":"say","category":"Genki Chapter 8"},
{"japanese":"いる","kanji":"","romanji":"iru","english":"to need","category":"Genki Chapter 8"},
{"japanese":"あそくなる","kanji":"","romanji":"asokunaru","english":"to be late","category":"Genki Chapter 8"},
{"japanese":"おもう","kanji":"","romanji":"omou","english":"to think","category":"Genki Chapter 8"},
{"japanese":"きる","kanji":"","romanji":"kiru","english":"to cut","category":"Genki Chapter 8"},
{"japanese":"つくる","kanji":"","romanji":"tsukuru","english":"to make","category":"Genki Chapter 8"},
{"japanese":"もっていく","kanji":"","romanji":"motteiku","english":"to take (a thing)","category":"Genki Chapter 8"},
{"japanese":"じろじろみる","kanji":"","romanji":"jirojiromiru","english":"to stare at","category":"Genki Chapter 8"},
{"japanese":"すてる","kanji":"","romanji":"suteru","english":"to throw away","category":"Genki Chapter 8"},
{"japanese":"はじめる","kanji":"","romanji":"hajimeru","english":"to begin","category":"Genki Chapter 8"},
{"japanese":"うんてんする","kanji":"","romanji":"untensuru","english":"to drive","category":"Genki Chapter 8"},
{"japanese":"せんたくする","kanji":"","romanji":"sentakusuru","english":"to do laundry","category":"Genki Chapter 8"},
{"japanese":"そうじする","kanji":"","romanji":"soujisuru","english":"to clean","category":"Genki Chapter 8"},
{"japanese":"でんわする","kanji":"","romanji":"denwasuru","english":"to call","category":"Genki Chapter 8"},
{"japanese":"りようりする","kanji":"","romanji":"ryourisuru","english":"to cook","category":"Genki Chapter 8"},
{"japanese":"いつも","kanji":"","romanji":"itsumo","english":"always","category":"Genki Chapter 8"},
{"japanese":"ううん","kanji":"","romanji":"uun","english":"uh-uh; no","category":"Genki Chapter 8"},
{"japanese":"うん","kanji":"","romanji":"un","english":"uh-huh; yes","category":"Genki Chapter 8"},
{"japanese":"かんぱい","kanji":"","romanji":"kanpai","english":"cheers (a toast)","category":"Genki Chapter 8"},
{"japanese":"ざんねん","kanji":"","romanji":"zannen","english":"that's too bad; dissapointing","category":"Genki Chapter 8"},
{"japanese":"まだ","kanji":"","romanji":"mada　","english":"not...yet","category":"Genki Chapter 8"},
{"japanese":"みんなで","kanji":"","romanji":"minnande","english":"all (of the people)","category":"Genki Chapter 8"},
{"japanese":"けさ","kanji":"","romanji":"kesa","english":"this morning","category":"Genki Chapter 8"},
{"japanese":"いいこ","kanji":"","romanji":"iiko","english":"good child","category":"Genki Chapter 9"},
{"japanese":"いる","kanji":"","romanji":"iru","english":"color","category":"Genki Chapter 9"},
{"japanese":"おべんとう","kanji":"","romanji":"obentou","english":"boxed lunch","category":"Genki Chapter 9"},
{"japanese":"かぶき","kanji":"","romanji":"kabuki","english":"kabuk-traditional theatrical art","category":"Genki Chapter 9"},
{"japanese":"ギター","kanji":"","romanji":"gitaa","english":"guitar","category":"Genki Chapter 9"},
{"japanese":"きょねん","kanji":"","romanji":"kyonen","english":"last year","category":"Genki Chapter 9"},
{"japanese":"くすり","kanji":"","romanji":"kusuri","english":"medicine","category":"Genki Chapter 9"},
{"japanese":"コンサート","kanji":"","romanji":"consato","english":"concert","category":"Genki Chapter 9"},
{"japanese":"こんど","kanji":"","romanji":"kondo","english":"near future","category":"Genki Chapter 9"},
{"japanese":"さくぶん","kanji":"","romanji":"sakubun","english":"essay; composition","category":"Genki Chapter 9"},
{"japanese":"しけん","kanji":"","romanji":"shiken","english":"exam","category":"Genki Chapter 9"},
{"japanese":"スキー","kanji":"","romanji":"sukii","english":"ski","category":"Genki Chapter 9"},
{"japanese":"せんげつ","kanji":"","romanji":"sengetsu","english":"last month","category":"Genki Chapter 9"},
{"japanese":"たんご","kanji":"","romanji":"tango","english":"word; vocabulary","category":"Genki Chapter 9"},
{"japanese":"ピアノ","kanji":"","romanji":"piano","english":"piano","category":"Genki Chapter 9"},
{"japanese":"ピザ","kanji":"","romanji":"piza","english":"pizza","category":"Genki Chapter 9"},
{"japanese":"びょうき","kanji":"","romanji":"byouki","english":"illness; sickness","category":"Genki Chapter 9"},
{"japanese":"くすりおのむ","kanji":"","romanji":"kusurionomu","english":"to take medicine","category":"Genki Chapter 9"},
{"japanese":"あおい","kanji":"","romanji":"aoi","english":"blue","category":"Genki Chapter 9"},
{"japanese":"おかい","kanji":"","romanji":"akai","english":"red","category":"Genki Chapter 9"},
{"japanese":"くろい","kanji":"","romanji":"kuroi","english":"black","category":"Genki Chapter 9"},
{"japanese":"さびしい","kanji":"","romanji":"sabishii","english":"lonely","category":"Genki Chapter 9"},
{"japanese":"しろい","kanji":"","romanji":"shiroi","english":"white","category":"Genki Chapter 9"},
{"japanese":"わかい","kanji":"","romanji":"wakai","english":"young","category":"Genki Chapter 9"},
{"japanese":"いじわるな","kanji":"","romanji":"ijiwaru(na)","english":"mean spirited","category":"Genki Chapter 9"},
{"japanese":"おどる","kanji":"","romanji":"odoru","english":"to dance","category":"Genki Chapter 9"},
{"japanese":"おわる","kanji":"","romanji":"owaru","english":"something ends","category":"Genki Chapter 9"},
{"japanese":"にんきがおる","kanji":"","romanji":"ninkigaoru","english":"to be popular","category":"Genki Chapter 9"},
{"japanese":"はじめる","kanji":"","romanji":"hajimeru","english":"(something) begins","category":"Genki Chapter 9"},
{"japanese":"ひく","kanji":"","romanji":"hiku","english":"to play (string instrument or piano)","category":"Genki Chapter 9"},
{"japanese":"もらう","kanji":"","romanji":"morau","english":"to get (from someone) (person ni thing o)","category":"Genki Chapter 9"},
{"japanese":"おぼえる","kanji":"","romanji":"oboeru","english":"to memorize","category":"Genki Chapter 9"},
{"japanese":"でる","kanji":"","romanji":"deru","english":"to appear; to attend (~ni); to exit (~o)","category":"Genki Chapter 9"},
{"japanese":"うんどうする","kanji":"","romanji":"undousuru","english":"to do physical excercise","category":"Genki Chapter 9"},
{"japanese":"さんぽする","kanji":"","romanji":"sanposuru","english":"to take a walk","category":"Genki Chapter 9"},
{"japanese":"～から","kanji":"","romanji":"~kara","english":"from...","category":"Genki Chapter 9"},
{"japanese":"ぜひ","kanji":"","romanji":"zehi","english":"by all means","category":"Genki Chapter 9"},
{"japanese":"ところで","kanji":"","romanji":"tokorode","english":"by the way","category":"Genki Chapter 9"},
{"japanese":"みんな","kanji":"","romanji":"mina","english":"all","category":"Genki Chapter 9"},
{"japanese":"もう","kanji":"","romanji":"mou","english":"already","category":"Genki Chapter 9"},
{"japanese":"ひとう","kanji":"一つ","romanji":"hitotsu","english":"one","category":"Genki Chapter 9"},
{"japanese":"ふたつ","kanji":"二つ","romanji":"futatsu","english":"two","category":"Genki Chapter 9"},
{"japanese":"みっつ","kanji":"三つ","romanji":"mittsu","english":"three","category":"Genki Chapter 9"},
{"japanese":"よっつ","kanji":"四つ","romanji":"yottsu","english":"four","category":"Genki Chapter 9"},
{"japanese":"いっつ","kanji":"五つ","romanji":"itsutsu","english":"five","category":"Genki Chapter 9"},
{"japanese":"むっつ","kanji":"むっつ","romanji":"muttsu","english":"six","category":"Genki Chapter 9"},
{"japanese":"ななつ","kanji":"七つ","romanji":"nanatsu","english":"seven","category":"Genki Chapter 9"},
{"japanese":"やっつ","kanji":"八つ","romanji":"yattsu","english":"eight","category":"Genki Chapter 9"},
{"japanese":"ここのつ","kanji":"ここのつ","romanji":"kokonotsu","english":"nine","category":"Genki Chapter 9"},
{"japanese":"とお","kanji":"十","romanji":"too","english":"ten","category":"Genki Chapter 9"}
];

